package com.easycart.db.entity;
// Generated 2016-7-8 20:23:30 by Hibernate Tools 4.3.1.Final

/**
 * FromAddress generated by hbm2java
 */
public class FromAddress implements java.io.Serializable {

	private Integer id;
	private Customer customer;
	private String fromAddress;
	private String fromCity;
	private String fromProvince;
	private String fromCountry;
	private String fromPhone;
	private String fromName;
	private Integer defaultAddress;

	public FromAddress() {
	}

	public FromAddress(Customer customer) {
		this.customer = customer;
	}

	public FromAddress(Customer customer, String fromAddress, String fromCity, String fromProvince, String fromCountry,
			String fromPhone, String fromName, Integer defaultAddress) {
		this.customer = customer;
		this.fromAddress = fromAddress;
		this.fromCity = fromCity;
		this.fromProvince = fromProvince;
		this.fromCountry = fromCountry;
		this.fromPhone = fromPhone;
		this.fromName = fromName;
		this.defaultAddress = defaultAddress;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getFromAddress() {
		return this.fromAddress;
	}

	public void setFromAddress(String fromAddress) {
		this.fromAddress = fromAddress;
	}

	public String getFromCity() {
		return this.fromCity;
	}

	public void setFromCity(String fromCity) {
		this.fromCity = fromCity;
	}

	public String getFromProvince() {
		return this.fromProvince;
	}

	public void setFromProvince(String fromProvince) {
		this.fromProvince = fromProvince;
	}

	public String getFromCountry() {
		return this.fromCountry;
	}

	public void setFromCountry(String fromCountry) {
		this.fromCountry = fromCountry;
	}

	public String getFromPhone() {
		return this.fromPhone;
	}

	public void setFromPhone(String fromPhone) {
		this.fromPhone = fromPhone;
	}

	public String getFromName() {
		return this.fromName;
	}

	public void setFromName(String fromName) {
		this.fromName = fromName;
	}

	public Integer getDefaultAddress() {
		return this.defaultAddress;
	}

	public void setDefaultAddress(Integer defaultAddress) {
		this.defaultAddress = defaultAddress;
	}

}
