package com.easycart.db.entity;
// Generated 2016-7-8 20:23:30 by Hibernate Tools 4.3.1.Final

/**
 * Banner generated by hbm2java
 */
public class Banner implements java.io.Serializable {

	private Integer id;
	private String imgHref;
	private String url;
	private Integer position;

	public Banner() {
	}

	public Banner(String imgHref, String url, Integer position) {
		this.imgHref = imgHref;
		this.url = url;
		this.position = position;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getImgHref() {
		return this.imgHref;
	}

	public void setImgHref(String imgHref) {
		this.imgHref = imgHref;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Integer getPosition() {
		return this.position;
	}

	public void setPosition(Integer position) {
		this.position = position;
	}

}
