package com.easycart.db.entity;
// Generated 2016-8-29 18:09:06 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name = "comment", catalog = "easycart")
public class Comment implements java.io.Serializable {

	private Integer id;
	private Product product;
	private String commentContent;
	private int createTime;
	private Set<Reply> replies = new HashSet<Reply>(0);

	public Comment() {
	}

	public Comment(Product product, String commentContent, int createTime) {
		this.product = product;
		this.commentContent = commentContent;
		this.createTime = createTime;
	}

	public Comment(Product product, String commentContent, int createTime, Set<Reply> replies) {
		this.product = product;
		this.commentContent = commentContent;
		this.createTime = createTime;
		this.replies = replies;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "comment_content", nullable = false, length = 512)
	public String getCommentContent() {
		return this.commentContent;
	}

	public void setCommentContent(String commentContent) {
		this.commentContent = commentContent;
	}

	@Column(name = "create_time", nullable = false)
	public int getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(int createTime) {
		this.createTime = createTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comment")
	public Set<Reply> getReplies() {
		return this.replies;
	}

	public void setReplies(Set<Reply> replies) {
		this.replies = replies;
	}

}
