package com.easycart.db.entity;
// Generated 2016-7-8 20:23:30 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Comment generated by hbm2java
 */
public class Comment implements java.io.Serializable {

	private Integer id;
	private Product product;
	private String commentContent;
	private int createTime;
	private Set replies = new HashSet(0);

	public Comment() {
	}

	public Comment(Product product, String commentContent, int createTime) {
		this.product = product;
		this.commentContent = commentContent;
		this.createTime = createTime;
	}

	public Comment(Product product, String commentContent, int createTime, Set replies) {
		this.product = product;
		this.commentContent = commentContent;
		this.createTime = createTime;
		this.replies = replies;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public String getCommentContent() {
		return this.commentContent;
	}

	public void setCommentContent(String commentContent) {
		this.commentContent = commentContent;
	}

	public int getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(int createTime) {
		this.createTime = createTime;
	}

	public Set getReplies() {
		return this.replies;
	}

	public void setReplies(Set replies) {
		this.replies = replies;
	}

}
