package com.easycart.db.entity;
// Generated 2016-8-29 18:09:06 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "easycart")
public class Customer implements java.io.Serializable {

	private Integer id;
	private String email;
	private String name;
	private String phone;
	private String password;
	private byte status;
	private double discount;
	private Date createTime;
	private Date modifyTime;
	private Set<Order> orders = new HashSet<Order>(0);
	private Set<OrderRecord> orderRecords = new HashSet<OrderRecord>(0);
	private Set<ToAddress> toAddresses = new HashSet<ToAddress>(0);
	private Set<Cart> carts = new HashSet<Cart>(0);
	private Set<FromAddress> fromAddresses = new HashSet<FromAddress>(0);

	public Customer() {
	}

	public Customer(String phone, String password, byte status, double discount) {
		this.phone = phone;
		this.password = password;
		this.status = status;
		this.discount = discount;
	}

	public Customer(String email, String name, String phone, String password, byte status, double discount,
			Date createTime, Date modifyTime, Set<Order> orders, Set<OrderRecord> orderRecords,
			Set<ToAddress> toAddresses, Set<Cart> carts, Set<FromAddress> fromAddresses) {
		this.email = email;
		this.name = name;
		this.phone = phone;
		this.password = password;
		this.status = status;
		this.discount = discount;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
		this.orders = orders;
		this.orderRecords = orderRecords;
		this.toAddresses = toAddresses;
		this.carts = carts;
		this.fromAddresses = fromAddresses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "email", length = 128)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "name", length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "phone", nullable = false, length = 128)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "password", nullable = false, length = 128)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Column(name = "discount", nullable = false, precision = 22, scale = 0)
	public double getDiscount() {
		return this.discount;
	}

	public void setDiscount(double discount) {
		this.discount = discount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_time", length = 19)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<OrderRecord> getOrderRecords() {
		return this.orderRecords;
	}

	public void setOrderRecords(Set<OrderRecord> orderRecords) {
		this.orderRecords = orderRecords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<ToAddress> getToAddresses() {
		return this.toAddresses;
	}

	public void setToAddresses(Set<ToAddress> toAddresses) {
		this.toAddresses = toAddresses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Cart> getCarts() {
		return this.carts;
	}

	public void setCarts(Set<Cart> carts) {
		this.carts = carts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<FromAddress> getFromAddresses() {
		return this.fromAddresses;
	}

	public void setFromAddresses(Set<FromAddress> fromAddresses) {
		this.fromAddresses = fromAddresses;
	}

}
