package com.easycart.db.entity;
// Generated 2016-8-29 18:09:06 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FromAddress generated by hbm2java
 */
@Entity
@Table(name = "from_address", catalog = "easycart")
public class FromAddress implements java.io.Serializable {

	private Integer id;
	private Customer customer;
	private String fromAddress;
	private String fromCity;
	private String fromProvince;
	private String fromCountry;
	private String fromPhone;
	private String fromName;
	private Integer defaultAddress;

	public FromAddress() {
	}

	public FromAddress(Customer customer) {
		this.customer = customer;
	}

	public FromAddress(Customer customer, String fromAddress, String fromCity, String fromProvince, String fromCountry,
			String fromPhone, String fromName, Integer defaultAddress) {
		this.customer = customer;
		this.fromAddress = fromAddress;
		this.fromCity = fromCity;
		this.fromProvince = fromProvince;
		this.fromCountry = fromCountry;
		this.fromPhone = fromPhone;
		this.fromName = fromName;
		this.defaultAddress = defaultAddress;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "from_address", length = 128)
	public String getFromAddress() {
		return this.fromAddress;
	}

	public void setFromAddress(String fromAddress) {
		this.fromAddress = fromAddress;
	}

	@Column(name = "from_city", length = 128)
	public String getFromCity() {
		return this.fromCity;
	}

	public void setFromCity(String fromCity) {
		this.fromCity = fromCity;
	}

	@Column(name = "from_province", length = 128)
	public String getFromProvince() {
		return this.fromProvince;
	}

	public void setFromProvince(String fromProvince) {
		this.fromProvince = fromProvince;
	}

	@Column(name = "from_country", length = 128)
	public String getFromCountry() {
		return this.fromCountry;
	}

	public void setFromCountry(String fromCountry) {
		this.fromCountry = fromCountry;
	}

	@Column(name = "from_phone", length = 45)
	public String getFromPhone() {
		return this.fromPhone;
	}

	public void setFromPhone(String fromPhone) {
		this.fromPhone = fromPhone;
	}

	@Column(name = "from_name", length = 45)
	public String getFromName() {
		return this.fromName;
	}

	public void setFromName(String fromName) {
		this.fromName = fromName;
	}

	@Column(name = "default_address")
	public Integer getDefaultAddress() {
		return this.defaultAddress;
	}

	public void setDefaultAddress(Integer defaultAddress) {
		this.defaultAddress = defaultAddress;
	}

}
