package com.easycart.db.entity;
// Generated 2016-8-29 18:09:06 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MenuAttr generated by hbm2java
 */
@Entity
@Table(name = "menu_attr", catalog = "easycart")
public class MenuAttr implements java.io.Serializable {

	private Integer id;
	private Menu menu;
	private String menuAttrName;
	private Set<ProductAttr> productAttrs = new HashSet<ProductAttr>(0);

	public MenuAttr() {
	}

	public MenuAttr(Menu menu, String menuAttrName) {
		this.menu = menu;
		this.menuAttrName = menuAttrName;
	}

	public MenuAttr(Menu menu, String menuAttrName, Set<ProductAttr> productAttrs) {
		this.menu = menu;
		this.menuAttrName = menuAttrName;
		this.productAttrs = productAttrs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "menu_id", nullable = false)
	public Menu getMenu() {
		return this.menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

	@Column(name = "menu_attr_name", nullable = false, length = 128)
	public String getMenuAttrName() {
		return this.menuAttrName;
	}

	public void setMenuAttrName(String menuAttrName) {
		this.menuAttrName = menuAttrName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menuAttr")
	public Set<ProductAttr> getProductAttrs() {
		return this.productAttrs;
	}

	public void setProductAttrs(Set<ProductAttr> productAttrs) {
		this.productAttrs = productAttrs;
	}

}
