package com.easycart.db.entity;
// Generated 2016-8-29 18:09:06 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "menu", catalog = "easycart", uniqueConstraints = @UniqueConstraint(columnNames = "name_en"))
public class Menu implements java.io.Serializable {

	private Integer id;
	private String nameCn;
	private String nameEn;
	private int level;
	private Integer position;
	private Integer fatherId;
	private Double unitePrice;
	private Double boxWeight;
	private Double otherCharge;
	private Set<ProductBrand> productBrands = new HashSet<ProductBrand>(0);
	private Set<MenuAttr> menuAttrs = new HashSet<MenuAttr>(0);
	private Set<Product> products = new HashSet<Product>(0);

	public Menu() {
	}

	public Menu(String nameCn, String nameEn, int level) {
		this.nameCn = nameCn;
		this.nameEn = nameEn;
		this.level = level;
	}

	public Menu(String nameCn, String nameEn, int level, Integer position, Integer fatherId, Double unitePrice,
			Double boxWeight, Double otherCharge, Set<ProductBrand> productBrands, Set<MenuAttr> menuAttrs,
			Set<Product> products) {
		this.nameCn = nameCn;
		this.nameEn = nameEn;
		this.level = level;
		this.position = position;
		this.fatherId = fatherId;
		this.unitePrice = unitePrice;
		this.boxWeight = boxWeight;
		this.otherCharge = otherCharge;
		this.productBrands = productBrands;
		this.menuAttrs = menuAttrs;
		this.products = products;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name_cn", nullable = false, length = 128)
	public String getNameCn() {
		return this.nameCn;
	}

	public void setNameCn(String nameCn) {
		this.nameCn = nameCn;
	}

	@Column(name = "name_en", unique = true, nullable = false, length = 128)
	public String getNameEn() {
		return this.nameEn;
	}

	public void setNameEn(String nameEn) {
		this.nameEn = nameEn;
	}

	@Column(name = "level", nullable = false)
	public int getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	@Column(name = "position")
	public Integer getPosition() {
		return this.position;
	}

	public void setPosition(Integer position) {
		this.position = position;
	}

	@Column(name = "father_id")
	public Integer getFatherId() {
		return this.fatherId;
	}

	public void setFatherId(Integer fatherId) {
		this.fatherId = fatherId;
	}

	@Column(name = "unite_price", precision = 10)
	public Double getUnitePrice() {
		return this.unitePrice;
	}

	public void setUnitePrice(Double unitePrice) {
		this.unitePrice = unitePrice;
	}

	@Column(name = "box_weight", precision = 22, scale = 0)
	public Double getBoxWeight() {
		return this.boxWeight;
	}

	public void setBoxWeight(Double boxWeight) {
		this.boxWeight = boxWeight;
	}

	@Column(name = "other_charge", precision = 22, scale = 0)
	public Double getOtherCharge() {
		return this.otherCharge;
	}

	public void setOtherCharge(Double otherCharge) {
		this.otherCharge = otherCharge;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menu")
	public Set<ProductBrand> getProductBrands() {
		return this.productBrands;
	}

	public void setProductBrands(Set<ProductBrand> productBrands) {
		this.productBrands = productBrands;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menu")
	public Set<MenuAttr> getMenuAttrs() {
		return this.menuAttrs;
	}

	public void setMenuAttrs(Set<MenuAttr> menuAttrs) {
		this.menuAttrs = menuAttrs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menu")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
