package com.easycart.db.entity;
// Generated 2016-8-29 18:09:06 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "order", catalog = "easycart")
public class Order implements java.io.Serializable {

	private Integer id;
	private Customer customer;
	private User user;
	private String trackingNum;
	private String payType;
	private Integer isPayed;
	private Double totalProductPrice;
	private Double totalFreight;
	private String customerMsg;
	private String adminMsg;
	private Integer status;
	private Integer createTime;
	private Integer modifyTime;
	private String fromName;
	private String fromPhone;
	private String fromAddress;
	private String toName;
	private String toPhone;
	private String toAddress;
	private Set<OrderRecord> orderRecords = new HashSet<OrderRecord>(0);

	public Order() {
	}

	public Order(Customer customer) {
		this.customer = customer;
	}

	public Order(Customer customer, User user, String trackingNum, String payType, Integer isPayed,
			Double totalProductPrice, Double totalFreight, String customerMsg, String adminMsg, Integer status,
			Integer createTime, Integer modifyTime, String fromName, String fromPhone, String fromAddress,
			String toName, String toPhone, String toAddress, Set<OrderRecord> orderRecords) {
		this.customer = customer;
		this.user = user;
		this.trackingNum = trackingNum;
		this.payType = payType;
		this.isPayed = isPayed;
		this.totalProductPrice = totalProductPrice;
		this.totalFreight = totalFreight;
		this.customerMsg = customerMsg;
		this.adminMsg = adminMsg;
		this.status = status;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
		this.fromName = fromName;
		this.fromPhone = fromPhone;
		this.fromAddress = fromAddress;
		this.toName = toName;
		this.toPhone = toPhone;
		this.toAddress = toAddress;
		this.orderRecords = orderRecords;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "tracking_num", length = 128)
	public String getTrackingNum() {
		return this.trackingNum;
	}

	public void setTrackingNum(String trackingNum) {
		this.trackingNum = trackingNum;
	}

	@Column(name = "pay_type", length = 45)
	public String getPayType() {
		return this.payType;
	}

	public void setPayType(String payType) {
		this.payType = payType;
	}

	@Column(name = "is_payed")
	public Integer getIsPayed() {
		return this.isPayed;
	}

	public void setIsPayed(Integer isPayed) {
		this.isPayed = isPayed;
	}

	@Column(name = "total_product_price", precision = 22, scale = 0)
	public Double getTotalProductPrice() {
		return this.totalProductPrice;
	}

	public void setTotalProductPrice(Double totalProductPrice) {
		this.totalProductPrice = totalProductPrice;
	}

	@Column(name = "total_freight", precision = 22, scale = 0)
	public Double getTotalFreight() {
		return this.totalFreight;
	}

	public void setTotalFreight(Double totalFreight) {
		this.totalFreight = totalFreight;
	}

	@Column(name = "customer_msg", length = 512)
	public String getCustomerMsg() {
		return this.customerMsg;
	}

	public void setCustomerMsg(String customerMsg) {
		this.customerMsg = customerMsg;
	}

	@Column(name = "admin_msg", length = 512)
	public String getAdminMsg() {
		return this.adminMsg;
	}

	public void setAdminMsg(String adminMsg) {
		this.adminMsg = adminMsg;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "create_time")
	public Integer getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Integer createTime) {
		this.createTime = createTime;
	}

	@Column(name = "modify_time")
	public Integer getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Integer modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "from_name")
	public String getFromName() {
		return this.fromName;
	}

	public void setFromName(String fromName) {
		this.fromName = fromName;
	}

	@Column(name = "from_phone")
	public String getFromPhone() {
		return this.fromPhone;
	}

	public void setFromPhone(String fromPhone) {
		this.fromPhone = fromPhone;
	}

	@Column(name = "from_address")
	public String getFromAddress() {
		return this.fromAddress;
	}

	public void setFromAddress(String fromAddress) {
		this.fromAddress = fromAddress;
	}

	@Column(name = "to_name")
	public String getToName() {
		return this.toName;
	}

	public void setToName(String toName) {
		this.toName = toName;
	}

	@Column(name = "to_phone")
	public String getToPhone() {
		return this.toPhone;
	}

	public void setToPhone(String toPhone) {
		this.toPhone = toPhone;
	}

	@Column(name = "to_address")
	public String getToAddress() {
		return this.toAddress;
	}

	public void setToAddress(String toAddress) {
		this.toAddress = toAddress;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "order")
	public Set<OrderRecord> getOrderRecords() {
		return this.orderRecords;
	}

	public void setOrderRecords(Set<OrderRecord> orderRecords) {
		this.orderRecords = orderRecords;
	}

}
