package com.easycart.db.entity;
// Generated 2016-8-29 18:09:06 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductImg generated by hbm2java
 */
@Entity
@Table(name = "product_img", catalog = "easycart")
public class ProductImg implements java.io.Serializable {

	private Integer id;
	private Product product;
	private String imgType;
	private Integer position;
	private Byte defaultImg;
	private String href;
	private String description;

	public ProductImg() {
	}

	public ProductImg(Product product, String imgType, String href) {
		this.product = product;
		this.imgType = imgType;
		this.href = href;
	}

	public ProductImg(Product product, String imgType, Integer position, Byte defaultImg, String href,
			String description) {
		this.product = product;
		this.imgType = imgType;
		this.position = position;
		this.defaultImg = defaultImg;
		this.href = href;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "img_type", nullable = false, length = 6)
	public String getImgType() {
		return this.imgType;
	}

	public void setImgType(String imgType) {
		this.imgType = imgType;
	}

	@Column(name = "position")
	public Integer getPosition() {
		return this.position;
	}

	public void setPosition(Integer position) {
		this.position = position;
	}

	@Column(name = "default_img")
	public Byte getDefaultImg() {
		return this.defaultImg;
	}

	public void setDefaultImg(Byte defaultImg) {
		this.defaultImg = defaultImg;
	}

	@Column(name = "href", nullable = false, length = 512)
	public String getHref() {
		return this.href;
	}

	public void setHref(String href) {
		this.href = href;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
