package com.easycart.db.entity;
// Generated 2016-8-29 18:09:06 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductAttr generated by hbm2java
 */
@Entity
@Table(name = "product_attr", catalog = "easycart")
public class ProductAttr implements java.io.Serializable {

	private int id;
	private MenuAttr menuAttr;
	private Product product;
	private ProductBrand productBrand;
	private String attrValue;

	public ProductAttr() {
	}

	public ProductAttr(int id, MenuAttr menuAttr, Product product, ProductBrand productBrand) {
		this.id = id;
		this.menuAttr = menuAttr;
		this.product = product;
		this.productBrand = productBrand;
	}

	public ProductAttr(int id, MenuAttr menuAttr, Product product, ProductBrand productBrand, String attrValue) {
		this.id = id;
		this.menuAttr = menuAttr;
		this.product = product;
		this.productBrand = productBrand;
		this.attrValue = attrValue;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "menu_attr_id", nullable = false)
	public MenuAttr getMenuAttr() {
		return this.menuAttr;
	}

	public void setMenuAttr(MenuAttr menuAttr) {
		this.menuAttr = menuAttr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_brand_id", nullable = false)
	public ProductBrand getProductBrand() {
		return this.productBrand;
	}

	public void setProductBrand(ProductBrand productBrand) {
		this.productBrand = productBrand;
	}

	@Column(name = "attr_value")
	public String getAttrValue() {
		return this.attrValue;
	}

	public void setAttrValue(String attrValue) {
		this.attrValue = attrValue;
	}

}
