package com.easycart.db.entity;
// Generated 2016-8-29 18:09:06 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProductBrand generated by hbm2java
 */
@Entity
@Table(name = "product_brand", catalog = "easycart")
public class ProductBrand implements java.io.Serializable {

	private Integer id;
	private Menu menu;
	private String brandNameCn;
	private String brandNameEn;
	private String brandImgUrl;
	private Set<ProductAttr> productAttrs = new HashSet<ProductAttr>(0);
	private Set<Product> products = new HashSet<Product>(0);

	public ProductBrand() {
	}

	public ProductBrand(Menu menu) {
		this.menu = menu;
	}

	public ProductBrand(Menu menu, String brandNameCn, String brandNameEn, String brandImgUrl,
			Set<ProductAttr> productAttrs, Set<Product> products) {
		this.menu = menu;
		this.brandNameCn = brandNameCn;
		this.brandNameEn = brandNameEn;
		this.brandImgUrl = brandImgUrl;
		this.productAttrs = productAttrs;
		this.products = products;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "menu_id", nullable = false)
	public Menu getMenu() {
		return this.menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

	@Column(name = "brand_name_cn", length = 128)
	public String getBrandNameCn() {
		return this.brandNameCn;
	}

	public void setBrandNameCn(String brandNameCn) {
		this.brandNameCn = brandNameCn;
	}

	@Column(name = "brand_name_en", length = 128)
	public String getBrandNameEn() {
		return this.brandNameEn;
	}

	public void setBrandNameEn(String brandNameEn) {
		this.brandNameEn = brandNameEn;
	}

	@Column(name = "brand_img_url", length = 512)
	public String getBrandImgUrl() {
		return this.brandImgUrl;
	}

	public void setBrandImgUrl(String brandImgUrl) {
		this.brandImgUrl = brandImgUrl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productBrand")
	public Set<ProductAttr> getProductAttrs() {
		return this.productAttrs;
	}

	public void setProductAttrs(Set<ProductAttr> productAttrs) {
		this.productAttrs = productAttrs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productBrand")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
