package com.easycart.db.entity;
// Generated 2016-7-8 20:23:30 by Hibernate Tools 4.3.1.Final

/**
 * ToAddress generated by hbm2java
 */
public class ToAddress implements java.io.Serializable {

	private Integer id;
	private Customer customer;
	private String toAddress;
	private String toCity;
	private String toProvince;
	private String toCountry;
	private String toPhone;
	private String toName;
	private Integer defaultAddress;

	public ToAddress() {
	}

	public ToAddress(Customer customer) {
		this.customer = customer;
	}

	public ToAddress(Customer customer, String toAddress, String toCity, String toProvince, String toCountry,
			String toPhone, String toName, Integer defaultAddress) {
		this.customer = customer;
		this.toAddress = toAddress;
		this.toCity = toCity;
		this.toProvince = toProvince;
		this.toCountry = toCountry;
		this.toPhone = toPhone;
		this.toName = toName;
		this.defaultAddress = defaultAddress;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getToAddress() {
		return this.toAddress;
	}

	public void setToAddress(String toAddress) {
		this.toAddress = toAddress;
	}

	public String getToCity() {
		return this.toCity;
	}

	public void setToCity(String toCity) {
		this.toCity = toCity;
	}

	public String getToProvince() {
		return this.toProvince;
	}

	public void setToProvince(String toProvince) {
		this.toProvince = toProvince;
	}

	public String getToCountry() {
		return this.toCountry;
	}

	public void setToCountry(String toCountry) {
		this.toCountry = toCountry;
	}

	public String getToPhone() {
		return this.toPhone;
	}

	public void setToPhone(String toPhone) {
		this.toPhone = toPhone;
	}

	public String getToName() {
		return this.toName;
	}

	public void setToName(String toName) {
		this.toName = toName;
	}

	public Integer getDefaultAddress() {
		return this.defaultAddress;
	}

	public void setDefaultAddress(Integer defaultAddress) {
		this.defaultAddress = defaultAddress;
	}

}
