package com.easycart.db.entity;
// Generated 2016-8-29 18:09:06 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ToAddress generated by hbm2java
 */
@Entity
@Table(name = "to_address", catalog = "easycart")
public class ToAddress implements java.io.Serializable {

	private Integer id;
	private Customer customer;
	private String toAddress;
	private String toCity;
	private String toProvince;
	private String toCountry;
	private String toPhone;
	private String toName;
	private Integer defaultAddress;

	public ToAddress() {
	}

	public ToAddress(Customer customer) {
		this.customer = customer;
	}

	public ToAddress(Customer customer, String toAddress, String toCity, String toProvince, String toCountry,
			String toPhone, String toName, Integer defaultAddress) {
		this.customer = customer;
		this.toAddress = toAddress;
		this.toCity = toCity;
		this.toProvince = toProvince;
		this.toCountry = toCountry;
		this.toPhone = toPhone;
		this.toName = toName;
		this.defaultAddress = defaultAddress;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "to_address", length = 128)
	public String getToAddress() {
		return this.toAddress;
	}

	public void setToAddress(String toAddress) {
		this.toAddress = toAddress;
	}

	@Column(name = "to_city", length = 128)
	public String getToCity() {
		return this.toCity;
	}

	public void setToCity(String toCity) {
		this.toCity = toCity;
	}

	@Column(name = "to_province", length = 128)
	public String getToProvince() {
		return this.toProvince;
	}

	public void setToProvince(String toProvince) {
		this.toProvince = toProvince;
	}

	@Column(name = "to_country", length = 128)
	public String getToCountry() {
		return this.toCountry;
	}

	public void setToCountry(String toCountry) {
		this.toCountry = toCountry;
	}

	@Column(name = "to_phone", length = 45)
	public String getToPhone() {
		return this.toPhone;
	}

	public void setToPhone(String toPhone) {
		this.toPhone = toPhone;
	}

	@Column(name = "to_name", length = 45)
	public String getToName() {
		return this.toName;
	}

	public void setToName(String toName) {
		this.toName = toName;
	}

	@Column(name = "default_address")
	public Integer getDefaultAddress() {
		return this.defaultAddress;
	}

	public void setDefaultAddress(Integer defaultAddress) {
		this.defaultAddress = defaultAddress;
	}

}
